server:
  image:
    tag: 1.0.2
  env:
    ROOT_PATH: "/cmg"
  resources:
    limits:
      cpu: 250m
      memory: 16Mi
    requests:
      cpu: 250m
      memory: 16Mi
  podAnnotations:
    prometheus.io/path: /cmg/metrics
    prometheus.io/port: "8080"
    prometheus.io/scrape: "true"
  ingress:
    enabled: true
    className: "contour"
    hosts:
      - host: watermelon.fritz.box
        paths:
          - path: /cmg
            pathType: Prefix
ui:
  image:
    tag: 1.2.1
  replicaCount: 1
  ingress:
    enabled: false
  httpproxy:
    enabled: true
    fqdn: goji.fritz.box
    prefix: /
    replacement: /
  resources:
    limits:
      cpu: 500m
      memory: 128Mi
    requests:
      cpu: 500m
      memory: 128Mi

seafarers:
  image:
    tag: 0.1.6
  resources:
    limits:
      cpu: 250m
      memory: 128Mi
    requests:
      cpu: 250m
      memory: 64Mi
  ingress:
    enabled: false
  httpproxy:
    enabled: true
    fqdn: watermelon.fritz.box
    prefix: /seafarers
    replacement: /

analytics:
  image:
    tag: 0.2.11
  resources:
    limits:
      cpu: 250m
      memory: 128Mi
    requests:
      cpu: 250m
      memory: 64Mi