{{- if .Values.server.httpproxy.enabled -}}
apiVersion: projectcontour.io/v1
kind: HTTPProxy
metadata:
  name: {{ include "cmg.fullname" . }}-servers
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "cmg.labels" . | nindent 4 }}
    app.kubernetes.io/component: servers
  {{- with .Values.server.httpproxy.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  ingressClassName: contour
  routes:
    - conditions:
        - prefix: {{ .Values.seafarers.httpproxy.prefix }}
      pathRewritePolicy:
        replacePrefix:
          - replacement: {{ .Values.seafarers.httpproxy.replacement }}
      services:
        - name: {{ include "cmg.fullname" . }}-seafarers
          port: {{ .Values.server.service.port }}
    - conditions:
        - prefix: {{ .Values.server.httpproxy.prefix }}
      pathRewritePolicy:
        replacePrefix:
          - replacement: {{ .Values.server.httpproxy.replacement }}
      services:
        - name: {{ include "cmg.fullname" . }}-server
          port: {{ .Values.server.service.port }}
  virtualhost:
    fqdn:  {{ .Values.server.httpproxy.fqdn }}
{{- end }}
