apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "cmg.fullname" . }}-ui
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "cmg.labels" . | nindent 4 }}
    app.kubernetes.io/component: ui
data:
  .env.production: |
    NEXT_PUBLIC_BACKEND_URL={{ .Values.ui.backend }}

