apiVersion: v1
kind: Service
metadata:
  name: {{ include "cmg.fullname" . }}-ui
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "cmg.labels" . | nindent 4 }}
    app.kubernetes.io/component: ui
spec:
  type: {{ .Values.ui.service.type }}
  ports:
    - port: {{ .Values.server.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "cmg.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: ui