nameOverride: ""
fullnameOverride: ""

server:
  image:
    repository: caladreas
    pullPolicy: IfNotPresent
    tag: 0.29.1
  labels: {}
  imagePullSecrets: null
  replicaCount: 3
  resources: {}
  podAnnotations: {}
  podSecurityContext: {}
  securityContext: {}
  nodeSelector: {}
  tolerations: []
  affinity: {}
  env:
    ROOT_PATH: "/cmg"
  autoscaling:
    enabled: true
    minReplicas: 3
    maxReplicas: 10
    targetCPUUtilizationPercentage: 80
    targetMemoryUtilizationPercentage: 80
  service:
    type: ClusterIP
    port: 80
    annotations: {}
  httpproxy:
    enabled: true
    fqdn: watermelon.fritz.box
    prefix: /cmg
    replacement: /cmg
  ingress:
    enabled: false
    className: ""
    annotations: {}
      # kubernetes.io/ingress.class: nginx
      # kubernetes.io/tls-acme: "true"
    hosts:
      - host: chart-example.local
        paths:
          - path: /
            pathType: ImplementationSpecific
    tls: []
    #  - secretName: chart-example-tls
    #    hosts:
    #      - chart-example.local


ui:
  image:
    repository: caladreas
    pullPolicy: IfNotPresent
    tag: 1.1.5
  backend: "http://watermelon.fritz.box/cmg"
  labels: {}
  imagePullSecrets: null
  replicaCount: 3
  resources: {}
  podAnnotations: {}
  podSecurityContext: {}
  securityContext: {}
  nodeSelector: {}
  tolerations: []
  affinity: {}
  env:
    NODE_ENV: production
    NEXT_PUBLIC_BACKEND_URL: "http://watermelon.fritz.box/cmg"
    NEXT_TELEMETRY_DISABLED: 1
  autoscaling:
    enabled: true
    minReplicas: 3
    maxReplicas: 10
    targetCPUUtilizationPercentage: 80
    targetMemoryUtilizationPercentage: 80
  service:
    type: ClusterIP
    port: 80
    annotations: {}
  httpproxy:
    enabled: true
    fqdn: goji.fritz.box
    prefix: /cmg
    replacement: /
  ingress:
    enabled: false
    className: ""
    annotations: {}
      # kubernetes.io/ingress.class: nginx
      # kubernetes.io/tls-acme: "true"
    hosts:
      - host: chart-example.local
        paths:
          - path: /
            pathType: ImplementationSpecific
    tls: []
    #  - secretName: chart-example-tls
    #    hosts:
    #      - chart-example.local

analytics:
  image:
    tag:

seafarers:
  image:
    tag:
